### ISSUE TITLE
can't run client

### ISSUE THREAD

**Issue by neilhuang007** [ArsenicClient/Arsenic#10]
here is the error code
```
`[18:00:37] [Client thread/INFO]: [net.minecraft.init.Bootstrap:printToSYSOUT:529]: ---- Minecraft Crash Report ----

WARNING: coremods are present:
  MixinLoader (Arsenic-v0.1.jar)
Contact their authors BEFORE contacting forge

// Hi. I'm Minecraft, and I'm a crashaholic.

Time: 23-7-19 ����6:00
Description: Initializing game

java.lang.NullPointerException: Initializing game
	at net.minecraft.client.Minecraft.handler$displayGuiScreen$zzm000(Minecraft.java:3658)
	at net.minecraft.client.Minecraft.displayGuiScreen(Minecraft.java:938)
	at net.minecraft.client.Minecraft.startGame(Minecraft.java:505)
	at net.minecraft.client.Minecraft.run(Minecraft.java:329)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraftforge.gradle.GradleStartCommon.launch(GradleStartCommon.java:97)
	at GradleStart.main(GradleStart.java:26)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at net.minecraft.client.Minecraft.handler$displayGuiScreen$zzm000(Minecraft.java:3658)
	at net.minecraft.client.Minecraft.displayGuiScreen(Minecraft.java:938)
	at net.minecraft.client.Minecraft.startGame(Minecraft.java:505)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.run(Minecraft.java:329)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraftforge.gradle.GradleStartCommon.launch(GradleStartCommon.java:97)
	at GradleStart.main(GradleStart.java:26)

-- System Details --
Details:
	Minecraft Version: 1.8.9
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_372, Amazon.com Inc.
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Amazon.com Inc.
	Memory: 611203632 bytes (582 MB) / 1568669696 bytes (1496 MB) up to 7559184384 bytes (7209 MB)
	JVM Flags: 0 total; 
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.19 Powered by Forge 11.15.1.2318 3 mods loaded, 3 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJA	FML{8.0.99.99} [Forge Mod Loader] (forgeBin-1.8.9-11.15.1.2318-1.8.9.jar) 
	UCHIJA	Forge{11.15.1.2318} [Minecraft Forge] (forgeBin-1.8.9-11.15.1.2318-1.8.9.jar) 
	Loaded coremods (and transformers): 
MixinLoader (Arsenic-v0.1.jar)
  arsenic.asm.ClassTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 528.79' Renderer: 'NVIDIA GeForce RTX 3060 Laptop GPU/PCIe/SSE2'
	Launched Version: 1.8.9
	LWJGL: 2.9.4
	OpenGL: NVIDIA GeForce RTX 3060 Laptop GPU/PCIe/SSE2 GL version 4.6.0 NVIDIA 528.79, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: No
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 20x 12th Gen Intel(R) Core(TM) i7-12700H
[18:00:37] [Client thread/INFO]: [net.minecraft.init.Bootstrap:printToSYSOUT:529]: #@!@# Game crashed! Crash report saved to: #@!@# C:\Users\neilhuang007\Documents\idea_projects\Arsenic\run\.\crash-reports\crash-2023-07-19_18.00.37-client.txt
AL lib: (EE) alc_cleanup: 1 device not closed

> Task :runClient FAILED

Execution failed for task ':runClient'.
> Process 'command 'C:\Users\neilhuang007\.jdks\corretto-1.8.0_372\bin\java.exe'' finished with non-zero exit value -1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

```

`

also, can't find Gradle start in starting instance
![image](https://github.com/ArsenicClient/Arsenic/assets/102778463/e9d051a4-2184-401c-92d1-2135af5069ca)

**Comment by Cosmic-SC** [comment]
change -cp Arsenic --> -cp Arsenic.main

**Comment by neilhuang007** [comment]
ok, let me try

**Comment by K-ov** [comment]
How'd it go

**Comment by Cosmic-SC** [comment]
idk probably worked since no reply
